syougun360/HadeMekaBattle

Assets/CharacterSelect.meta
Assets/CharacterSelect/Resource.meta
Assets/CharacterSelect/Resource/Blue Renjai.prefab
Assets/CharacterSelect/Resource/Blue Renjai.prefab.meta
Assets/CharacterSelect/Resource/Green Renjai.prefab
Assets/CharacterSelect/Resource/Green Renjai.prefab.meta
Assets/CharacterSelect/Resource/Momo Renjai.prefab
Assets/CharacterSelect/Resource/Momo Renjai.prefab.meta
Assets/CharacterSelect/Resource/Red  Renjai.prefab
Assets/CharacterSelect/Resource/Red  Renjai.prefab.meta
Assets/CharacterSelect/Resource/Yellow Renjai.prefab
Assets/CharacterSelect/Resource/Yellow Renjai.prefab.meta
Assets/CharacterSelect/Script.meta
Assets/CharacterSelect/Texture.meta
Assets/CharacterSelect/Texture/Blue.mat
Assets/CharacterSelect/Texture/Blue.mat.meta
Assets/CharacterSelect/Texture/Green.mat
Assets/CharacterSelect/Texture/Green.mat.meta
Assets/CharacterSelect/Texture/Momo.mat
Assets/CharacterSelect/Texture/Momo.mat.meta
Assets/CharacterSelect/Texture/Red.mat
Assets/CharacterSelect/Texture/Red.mat.meta
Assets/CharacterSelect/Texture/Yellow.mat
Assets/CharacterSelect/Texture/Yellow.mat.meta
Assets/Scene/CharacterSelect.unity

* 実装したこと
* cudeを5種類実装
* Materialを5種類実装

#551 5人分のキャラの表示

---

Assets/Battle/Bullet.meta
Assets/Battle/Bullet/Bullet.prefab
Assets/Battle/Bullet/Bullet.prefab.meta
Assets/Battle/Bullet/BulletTest.unity
Assets/Battle/Bullet/BulletTest.unity.meta
Assets/Battle/Bullet/Scripts.meta
Assets/Battle/Bullet/Scripts/BulletMover.cs
Assets/Battle/Bullet/Scripts/BulletMover.cs.meta
Assets/Battle/Bullet/Scripts/BulletRotater.cs
Assets/Battle/Bullet/Scripts/BulletRotater.cs.meta
Assets/Battle/Bullet/Scripts/BulletShooter.cs
Assets/Battle/Bullet/Scripts/BulletShooter.cs.meta
Assets/Battle/Bullet/Scripts/BulletValue.cs
Assets/Battle/Bullet/Scripts/BulletValue.cs.meta

* 単純なパラメータ(完全版ではない)
* 弾(仮)が向いている方向に前進
* 確認用のシーン
* BulletValue.cs
* 簡易版
* BulletMover.cs
* BulletShooter.cs
* 一先ず動かすのが目的なので、こちらは未実装

簡易パラメータを実装し、球が向いている方向に前進

---

Assets/Scene/Director.cs
Assets/Scene/Director.cs.meta
Assets/Scene/Director.prefab
Assets/Scene/Director.prefab.meta
Assets/Scene/FadeManager.cs
Assets/Scene/FadeManager.cs.meta
Assets/Scene/IScene.cs
Assets/Scene/IScene.cs.meta
Assets/Scene/SceneManager.cs
Assets/Scene/SceneManager.cs.meta
Assets/Scene/Title.unity
Assets/Title.meta
Assets/Title/TitleManager.cs
Assets/Title/TitleManager.cs.meta
Assets/Title/TitleManager.prefab
Assets/Title/TitleManager.prefab.meta
ProjectSettings/EditorBuildSettings.asset

* シーンを切り替えるためのシステムを作りました。
* やり方を下記の通りです。
* `SceneManager.Instance.StartChange();` を使ってください！
* 引数に、次に行くシーンのenum型・シーンに切り替える時間（フェード時間）
以上です。
* SceneManager.cs
* シーンの管理者です。
* シーンを切り替えの処理は、ここにあります。
* Director.cs
* アプリケーションの設定はすべてここでします。
* IScene.cs
* 各シーンのインターフェイス部分になります。
* FadeManager.cs
* シーンを遷移するときにおこるフェードの処理がある。
* TitleManager.cs
* 試しに作成したスクリプト。
* 遷移の処理が書かれている。
以上です。

#693 シーンチェンジシステム実装

---

Assets/Battle/Bullet/BulletTest.unity
Assets/Battle/Bullet/Prefavs.meta
Assets/Battle/Bullet/Prefavs/Bullet.prefab
Assets/Battle/Bullet/Prefavs/Bullet.prefab.meta
Assets/Battle/Bullet/Prefavs/Missile.prefab
Assets/Battle/Bullet/Prefavs/Missile.prefab.meta
Assets/Battle/Bullet/Scripts/Base/BulletBasePalametar.cs
Assets/Battle/Bullet/Scripts/Bullet/BulletMover.cs
Assets/Battle/Bullet/Scripts/Missile/MissileMover.cs
Assets/Battle/Bullet/Scripts/Missile/MissileMover.cs.meta
Assets/Battle/Bullet/Scripts/Missile/MissilePalametar.cs
Assets/Battle/Bullet/Scripts/Missile/MissileRotater.cs
Assets/Battle/Bullet/Scripts/Missile/MissileRotater.cs.meta

* ミサイルの挙動実装
* 基本的な動きに限る
* ミサイルのプレハブ化
* MissilePalametor.cs
* MissileMover.cs
* MissileRotater.cs

ホーミングミサイルの挙動

---

Assets/Battle/Player/BoostManager.cs
Assets/Battle/Player/BoostManager.cs.meta
Assets/Battle/Player/Player.prefab
Assets/Battle/Player/PlayerBooster.cs
Assets/Battle/Player/PlayerJumper.cs
Assets/Battle/Player/PlayerMover.cs
Assets/Battle/Player/PlayerQuickBooster.cs
Assets/Battle/Player/PlayerQuickBooster.cs.meta
Assets/Scene/Battle.unity
ProjectSettings/InputManager.asset

* クイックブースト(緊急回避)の実装
* 向いている方向に対して左右にダッシュできるようにした。
* __連続で使用可能。__
* __ブースト値を消費する。__
* #571ブースト値（減少するアレ）の変数を実装
* 0.0f~100.0fの範囲で使用
* GetCompornent等でスクリプトを取得し、Quantityで取得可能。
* __加算、減算する場合はAddQuantity（）関数を呼ぶ__こと。
* #572ブースト使用時にブースト値が減少するように設定
* 上記のAddQuantity()関数にて実装。
* 各スクリプトにて減少量をインスペクタを設定できる。
* #573出力比を扱う変数を用意し、ブースト値の変化量と移動量が変化するように設定
* BoostManager.cs内にてboostRatio変数を定義。
* 現状では1.0~2.0fの間で変化する。
* #575ブースト値が自然回復するように設定
* BoostManager.cs内Update()関数でAutoRegain()関数が呼ばれ回復する。
* #576ブースト値が消費分なければ使用不可能にする機能の実装
* BoostManager.csにてCanUseBoost()関数を実装。
* 消費する予定の数値を引数で渡すことで使用できるかどうかをbool文で返す。
* 消費可能...true 　足りない、消費できない...false
* スクリプトの使い方に関しては上記を見る事。
* LeftShiftで左へ緊急回避、RightShiftで右へ緊急回避する。
* __ブースター使用キーをLeftCtrlに変更。__

#567ブースト上限の実装

---

Assets/Battle/Player/EnergyManager.cs
Assets/Battle/Player/EnergyManager.cs.meta
Assets/Battle/Player/Player.prefab
Assets/Scene/Battle.unity

* EnergyManager.csを追加、内部でenergyRatio変数を実装。
* EnergyRatioプロパティにて取得、設定する。__扱える範囲は-1.0f ~ 1.0fです。__
1. __[SerializeField]EnergyManager__型で__変数__を用意する。
2. 用意した__変数__を使い、プロパティである__EnergyRatio__を得る。
3. 得た__EnergyRatio__を使って各種計算をする。
4. __インスペクタでPlayerのEnergyManagerを渡す。__
:ghost:

電力を扱うマネージャーの実装

---

Assets/Battle/Player/BuildManager.cs
Assets/Battle/Player/BuildManager.cs.meta
Assets/Scene/Battle.unity

* プレイヤーが選択したロボット、武器の情報を管理するクラスを設計しました。
* BuildManager.cs内にて__RobotTexutreID__と__WeaponList配列__を用意、ここに保存する。
* __RobotTextureID__は__プロパティ__、__WeaponList__は__アクセサー__を用意してあります。
* RobotTextureIDはプロパティとして使用してください。ゲッターセッターどちらも使用できます。
* -1がエラーコードとなっています。
* WeaponListにデータを__設定__する場合、__SetWeapon(装備する箇所、装備する武器のID)を使用__してください。
* WeaponListからデータを__取得__する場合、__WeaponInformationを呼び返り値を使用__してください。

マシンの情報を管理するマネージャーの実装

---

Assets/Battle/Player/BuildManager.cs
Assets/Battle/Player/Player.prefab
Assets/Scene/Battle.unity

ロボのテクスチャを扱う変数の追加

---

Assets/Battle/Bullet/Scripts/Shooter.meta
Assets/Battle/Player/PlayerShooter.cs
Assets/Battle/Player/PlayerShooter.cs.meta

* Mr.KuragaiがWeaponの機能を作るので後ほど修正するはずです。

射撃の機能のテスト実装

---

Assets/Battle/Enemy.meta
Assets/Battle/Enemy/EnemyListManager.cs
Assets/Battle/Enemy/EnemyListManager.cs.meta
Assets/Battle/Enemy/EnemyManager.prefab
Assets/Battle/Enemy/EnemyManager.prefab.meta
Assets/Scene/Battle.unity

* #645 敵の一覧を管理するオブジェクトの生成
* __EnemyManager__というゲームオブジェクトを実装。
* __EnemyListManager.cs__を追加
* __List<GameObject>型__の__enemyList__を用意しました。
1. __EnemyManager__を取得する。
2. 取得した__EnemyManager__のコンポーネントである__EnemyListManager__を取得する。
3. 取得した__EnemyListManager__に対して__Add(GameObject)__で__リストに追加__する。
4. __EnemyListManager__に対して__GetEnemy(int)__で指定した配列番号にある__敵を得る__。<br>
*__もし存在しない場合nullを返し、コンソールにエラー文を出す__
5. __EnemyListManager__に対して__GetEnemyList()__で__Listを取得__できます。
```
[SerializeField] GameObject enemyManager = null;
enemyManager.Add(this.gameObject);
var enemy = ememyManager.GetEnemy(0);//リストの1つ目のエネミーを得る
var enemyList = enemyManager.GetEnemyList();//リスト全体を得る
```

敵の一覧を管理するオブジェクトの実装

---

Assets/Battle/Player/Player.prefab
Assets/Battle/Player/PlayerQuickBooster.cs
Assets/Effect.meta
Assets/Effect/Smoke.prefab
Assets/Effect/Smoke.prefab.meta
Assets/EffekseerEmitterDestroyer.cs
Assets/EffekseerEmitterDestroyer.cs.meta
Assets/Plugins/Effekseer/EffekseerEmitter.cs

* エフェクトを生成するメソッドを作成した。
* エフェクトの自動で削除するスクリプトを削除
* EffekseerEmitter.Create(GameObject,Vector3)を使ってください。
* エフェクトを生成するスクリプトでGameObjectをアタッチして、上記のCreateで生成してください
* エフェクトのプレハブにEffekseerEmitterDestroyerをコンポーネントしてください！
* これで生成して、再生し終わると自動的に消えます。
* EffekseerEmitter.cs
* EffekseerEmitterDestroyer.cs
* NetworkView
* NetworkIdentity
* NetworkTransform
以上です。

エフェクトの自動削除、生成のメソッド実装

---

Assets/CharacterSelect/Script/CharacterChanger.cs
Assets/CharacterSelect/Script/HorizontalCharacter.cs
Assets/Scene/CharacterSelect.unity
Assets/StreamingAssets/Effekseer/Sound.meta

* 実装した内容
* キャラクターの切り替え
* 変更したスクリプト
* HorizontalCharacter.cs
* CharacterChanger.cs

#549 十字キー(仮)でキャラ変更

---

Assets/Battle/Enemy/EnemyListManager.cs
Assets/Battle/Enemy/EnemyManager.prefab
Assets/Battle/Player/TargetSystem.meta
Assets/Battle/Player/TargetSystem/TargetSystem.cs
Assets/Battle/Player/TargetSystem/TargetSystem.cs.meta
Assets/Network/NetworkPlayerSetup.cs

* EnemyManagerに画面の中心から一定距離にいる敵を検知するTargetSystem.csの実装
1. EnemyManagerのTargetSystemコンポーネントを取得
2. TargetSystem.RefreshInsideObjects()によって一覧を更新する。
3. 上記関数は戻り値がListなのでそれで内部にいる敵をListで取得できます。
```
EnemyManager enemyManager = null;
enemyManager = GameObject.Find("EnemyManager");///EnemyManagerを得る
var targetSystem = enemyManager.GetCompornent<TargetSystem>();///TargetSystemスクリプトを得る
var insideObjects =  targetSystem.RefreshInsideObjects();///画面内にいる敵の一覧を得る
```

#570レティクル内に敵がいるかどうかの判断ができる機能の実装

---

ProjectSettings/InputManager.asset

* Input.AxisにXbox360のコントローラーに対応させました。
* 左スティック : 移動
* 右スティック : 視点の左右移動
* Yボタン : ジャンプ
* Xボタン : ブースト
* RBボタン : 右手武器使用
* LBボタン : 左手武器使用
* Rトリガー : 右に緊急回避
* Lトリガー : 左に緊急回避

InputManagerをXbox360のコントローラーに対応させました

---

Assets/Battle/Player/BoostManager.cs
Assets/Battle/Player/HealthManager.cs
Assets/Battle/Player/Player.prefab
Assets/Battle/UI.meta
Assets/Battle/UI/AttachCamera.cs
Assets/Battle/UI/AttachCamera.cs.meta
Assets/Battle/UI/Player.meta
Assets/Battle/UI/Player/BoostBarScaler.cs
Assets/Battle/UI/Player/BoostBarScaler.cs.meta
Assets/Battle/UI/Player/HPBarScaler.cs
Assets/Battle/UI/Player/HPBarScaler.cs.meta
Assets/Battle/UI/UICanvas.prefab
Assets/Battle/UI/UICanvas.prefab.meta
Assets/Interface/Battle/HitpointBar_Frame.png.meta
Assets/Interface/Battle/HitpointBar_Gauge.png.meta
Assets/Network/NetworkPlayerSetup.cs
Assets/Scene/Battle.unity

* HPバーの表示
* ブーストゲージの表示
** どちらも仮素材です!! **

HPバーとブーストゲージの表示の実装

---

Assets/Battle/Bullet/Prefavs/Missile_PariSiteJan.prefab
Assets/Battle/Player/HealthManager.cs
Assets/Resources/Prefabs/Bullet_HRTK.prefab.meta
Assets/Resources/Prefabs/Bullet_SGMT.prefab.meta
Assets/Resources/Prefabs/Bullet_TKG.prefab.meta
Assets/Resources/Prefabs/Bullet_YMD.prefab.meta
Assets/Resources/Prefabs/Lancher_L_F_GK.prefab.meta
Assets/Resources/Prefabs/Lancher_M_F_DS.prefab.meta
Assets/Resources/Prefabs/Lancher_M_T_GK.prefab.meta
Assets/Resources/Prefabs/Missile_AutoMojan.prefab.meta
Assets/Resources/Prefabs/Missile_End_of_a_Tard.prefab.meta
Assets/Resources/Prefabs/Missile_KogaMajan.prefab.meta
Assets/Resources/Prefabs/RBullet_Fuzitaka.prefab.meta
Assets/Resources/Prefabs/RBullet_Minami.prefab.meta
Assets/Resources/Prefabs/RBullet_Raigaku.prefab.meta

* __HealthManager.cs__に__物理のダメージ__と__電気ダメージ__による計算の違いを加味したHP減算処理を追加
* __HealthManager__を得て、__PhysicalDamage（int）関数__または__EnergyDamage(int)関数__を使用する。

ダメージを与える関数の追加

---

Assets/Battle/Drone/Material/test.mat
Assets/Battle/Enemy/EnemyListManager.cs
Assets/Network/NetworkManagerSetup.cs

* __EnemyListManager__を__リセット__する関数を実装
* __NetworkManager__で消失時の処理にて実行するようにしました。

クライアントが消滅したときに出るエラーの修正

---

Assets/Battle/Drone/Prefab.meta
Assets/Effect/BoostStrength.prefab
Assets/Effect/BoostStrength.prefab.meta
Assets/Effect/BoostWeak.prefab
Assets/Effect/BoostWeak.prefab.meta
Assets/Effect/EnergyBullet.prefab
Assets/Effect/EnergyBullet.prefab.meta
Assets/Effect/EnergyFiring.prefab
Assets/Effect/EnergyFiring.prefab.meta
Assets/Effect/EnergyHit.prefab
Assets/Effect/EnergyHit.prefab.meta
Assets/Effect/Explosion.prefab
Assets/Effect/Explosion.prefab.meta
Assets/Effect/LiveAmmunitionFiring.prefab
Assets/Effect/LiveAmmunitionFiring.prefab.meta
Assets/Effect/LiveBullet.prefab
Assets/Effect/LiveBullet.prefab.meta
Assets/Effect/LiveHit.prefab
Assets/Effect/LiveHit.prefab.meta
Assets/Effect/PowerAttack.prefab
Assets/Effect/PowerAttack.prefab.meta
Assets/Effect/PowerDefence.prefab
Assets/Effect/PowerDefence.prefab.meta
Assets/Effect/Smoke.prefab
Assets/Scene/Battle.unity

パーティクルのプレハブ化

---

Assets/Battle/Bullet/Scripts/Base/BulletBasePalametar.cs
Assets/Battle/Bullet/Scripts/DataBase/BulletDataBase.cs
Assets/Battle/Bullet/Scripts/DataBase/BulletPalamaterData.cs
Assets/Battle/Bullet/Scripts/HitChecker.cs
Assets/Resources/DataBase/BulletData.json

* jsonから取得されたデータベースからパラメータを取得できるようにしました

データベースからパラメータを取得

---

Assets/Battle/TimeManager.cs

* TimeManager.NowTimeSecondをstatic化しました。
* ```TimeManager.NowTimeSecond```で経過時間を取得できます。

NowTimeSecondのstatic化

---

Assets/Battle/Player/Player.prefab
Assets/Battle/SceneManager/TimeManager.cs
Assets/Battle/SceneManager/TimeManager.cs.meta
Assets/Network/NetworkPlayerSetup.cs
ProjectSettings/TagManager.asset

* 未定義のtagを設定しようとしてバグが発生していたのでタグを用意しました。
__私のせいです。許して。__ :sob: 
* ファイルの場所を変更
* TimeManager.csをSceneManagerファイル内に移動。

ネットワークセットアッププレイヤーのバグ消しをしました

---

Assets/Battle/Bullet/Resources/Prefabs/Bullet_HRTK.prefab
Assets/Battle/Bullet/Resources/Prefabs/Bullet_HRTK.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/Bullet_SGMT.prefab
Assets/Battle/Bullet/Resources/Prefabs/Bullet_SGMT.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/Bullet_TKG.prefab
Assets/Battle/Bullet/Resources/Prefabs/Bullet_TKG.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/Bullet_YMD.prefab
Assets/Battle/Bullet/Resources/Prefabs/Bullet_YMD.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/Lancher_L_F_GK.prefab
Assets/Battle/Bullet/Resources/Prefabs/Lancher_L_F_GK.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/Lancher_M_F_DS.prefab
Assets/Battle/Bullet/Resources/Prefabs/Lancher_M_F_DS.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/Lancher_M_T_GK.prefab
Assets/Battle/Bullet/Resources/Prefabs/Lancher_M_T_GK.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/Missile_AutoMojan.prefab
Assets/Battle/Bullet/Resources/Prefabs/Missile_AutoMojan.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/Missile_End_of_a_Tard.prefab
Assets/Battle/Bullet/Resources/Prefabs/Missile_End_of_a_Tard.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/Missile_KogaMajan.prefab
Assets/Battle/Bullet/Resources/Prefabs/Missile_KogaMajan.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/Missile_PariSitejan.prefab
Assets/Battle/Bullet/Resources/Prefabs/Missile_PariSitejan.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/RBullet_Fuzitaka.prefab
Assets/Battle/Bullet/Resources/Prefabs/RBullet_Fuzitaka.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/RBullet_Minami.prefab
Assets/Battle/Bullet/Resources/Prefabs/RBullet_Minami.prefab.meta
Assets/Battle/Bullet/Resources/Prefabs/RBullet_Raigaku.prefab
Assets/Battle/Bullet/Resources/Prefabs/RBullet_Raigaku.prefab.meta

弾丸のプレハブ再設定

---

Assets/Battle/Player/BoostManager.cs
Assets/Battle/UI/Player/BoostBarScaler.cs
Assets/Battle/UI/UICanvas.prefab

* ブースト残量が足りない場合にゲージの色が変わるようにしました。
* ブースト、HPのバーを画面右上に移動しました
* 仮のUIです！！

ブーストのUIに残量が足りなかった場合の処理を追加しました

---

Assets/Battle/Player/Player.prefab
Assets/Battle/Player/PlayerHider.cs
Assets/Measure.meta
Assets/Measure/FpsMeasure.cs
Assets/Measure/FpsMeasure.cs.meta
Assets/Measure/Measure.prefab
Assets/Measure/Measure.prefab.meta
Assets/Measure/RrtMeasure.cs
Assets/Measure/RrtMeasure.cs.meta
Assets/Scene/Battle.unity

* FPSを計算して、Textで描画した。
* RRT(通信レート)をTextで描画した
以上です

FPSとRRTを描画実装
